# Generated by Django 5.1 on 2024-08-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='name',
        ),
    ]
