# Generated by Django 5.1 on 2024-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('photo', models.URLField()),
                ('will_receive_bonus', models.BooleanField(default=False)),
            ],
        ),
    ]
