# Generated by Django 5.1 on 2024-09-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_nullblankdemi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NullBlankDemi',
            new_name='NullBlankDemo',
        ),
    ]
