# Generated by Django 5.1 on 2024-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_nullblankdemi_nullblankdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='will_receive_bonus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
