# Generated by Django 5.1 on 2024-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_employee_will_receive_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Junior', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='will_receive_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
