# Generated by Django 5.1 on 2024-09-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_department_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
