# Generated by Django 5.1 on 2024-09-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
