# Generated by Django 5.1 on 2024-09-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_employee_department_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code_name', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='web.project'),
        ),
    ]
