# Generated by Django 5.1 on 2024-09-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_employee_options_department_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
